version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: nba_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nba_stats
            MYSQL_USER: nba_user
            MYSQL_PASSWORD: nba_pass
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

volumes:
    mysql_data:
